repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        args: ["--line-length=79"]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.238
    hooks:
      - id: ruff
        args: [
          "--line-length=79",
          "--select=E,F,W,C,I,Q",
          "--ignore=E402",
          "--unfixable=FBT",
          "--fix",
        ]
