[tool.pytest.ini_options]
testpaths = "tests"
asyncio_mode = "auto"
addopts = "--maxfail=1 --capture=no --verbose --tb=short --cov --cov-report=term-missing"

[tool.coverage.run]
omit = [
    ".venv/*",
    "venv/*",
    ".env/*",
    "env/*",
    "tests/*"
]

[tool.isort]
atomic = true
profile = "black"
line_length = 79
skip_gitignore = true

[tool.black]
line-length = 79

[tool.ruff]
line-length = 79
select = ["E", "F", "W", "C", "I", "Q"]
ignore = ["E402"]
unfixable = ["FBT"]
fix = true
